---
- hosts: localhost
  any_errors_fatal: true

  vars:
    userlocale: "ru_RU.UTF-8"
    baseuser: "{{ ansible_env.USER }}"
    homedir: "{{ ansible_env.HOME }}"
    projectdir: "{{ ansible_env.HOME }}/project"
    phpVersion: 7.0

  environment:
    LC_CTYPE: "{{ userlocale }}"
    LC_COLLATE: "{{ userlocale }}"

  tasks:
    - set_fact:
        prod_env: true
      tags: ["always"]
    - set_fact:
        prod_env: false
      tags: ["dev", "always"]
    - set_fact:
        phpVersion: 7.1
      tags: ["php71"]

    - name: php started
      service: name="php{{ phpVersion }}-fpm" state=restarted
      become: true
      tags: ["php7"]
    - name: nginx started
      service: name=nginx state=restarted
      become: true
      tags: ["nginx"]
    - name: postgresql started
      service: name=postgresql state=restarted
      become: true
      tags: ["postgresql"]
    - name: elasticsearch started
      service: name=elasticsearch state=restarted
      become: true
      tags: ["elasticsearch"]
    - name: redis-server started
      service: name=redis-server state=restarted
      become: true
      tags: ["redis"]

