---
- hosts: localhost
  any_errors_fatal: true

  vars:
    userlocale: "ru_RU.UTF-8"
    baseuser: "{{ ansible_env.USER }}"
    homedir: "{{ ansible_env.HOME }}"
    projectdir: "{{ ansible_env.HOME }}/project"

  environment:
    LC_CTYPE: "{{ userlocale }}"
    LC_COLLATE: "{{ userlocale }}"

  tasks:
#    - name: "Test composer.json exists"
#      stat: path={{ projectdir }}/composer.json
#      register: composerjson_stat
#      tags: ["composer_install"]
#    - debug: msg="***** Next action (composer install) can take a long time (>5 min) *****"
#      tags: ["composer_install"]
#    - name: "composer install"
#      shell: "{{ homedir }}/bin/composer install --no-interaction"
#      args:
#        chdir: "{{ projectdir }}"
#      when: "composerjson_stat.stat.exists == True"
#      register: composer_update
#      changed_when: "'Nothing to install or update' not in composer_update.stderr"
#      tags: ["composer_install"]

#    - name: "Run database Symfony migrations"
#      shell: "php app/console doctrine:migrations:migrate --no-interaction"
#      args:
#        chdir: "{{ projectdir }}"
#      register: migrate_run
#      changed_when: "'No migrations to execute' not in migrate_run.stdout"
#      failed_when: false
#      tags: ["migration"]
#    - name: "Load SQL dump using psql"
#      shell: "psql < {{ projectdir }}/schema.sql"
#      tags: ["migration"]

#    - name: "Test package.json exists"
#      stat: path={{ projectdir }}/package.json
#      register: packagejson_stat
#      tags: ["npm_install"]
#    - debug: msg="***** Next action (npm install) can take a long time *****"
#      tags: ["npm_install"]
#    - name: "NPM install"
#      shell: "npm i --no-bin-links || npm i --no-bin-links"
#      args:
#        chdir: "{{ projectdir }}"
#      register: npm_update
#      changed_when: "npm_update.stdout"
#      when: "packagejson_stat.stat.exists == True"
#      tags: ["npm_install"]
#    - name: "NPM rebuild sass"
#      shell: "npm rebuild node-sass"
#      args:
#        chdir: "{{ projectdir }}"
#      register: npm_sass_update
#      changed_when: "'Start downloading' in npm_sass_update.stdout"
#      tags: ["nodejs-saas", "dev"]

#    - name: "Test webpack.config.js exists"
#      stat: path={{ projectdir }}/webpack.config.js
#      register: webpackconfig_stat
#      tags: ["webpack"]
#    - name: "Run webpack for first build"
#      shell: "{{ homedir }}/bin/webpack"
#      args:
#        chdir: "{{ projectdir }}"
#      register: webpack_start
#      when: "webpackconfig_stat.stat.exists == True"
#      changed_when: true
#      failed_when: 'webpack_start.rc'
#      tags: ["webpack"]

#    - name: "Check Yii1 framework 1.1.17"
#      stat: path={{ homedir }}/yii
#      register: yii
#      tags: ["yii1"]
#    - name: "Install Yii1 framework 1.1.17"
#      git: repo=https://github.com/yiisoft/yii.git dest={{ homedir }}/yii-1.1.17 version=1.1.17
#      when: yii.stat.islnk is not defined
#      tags: ["yii1"]
#    - name: "Link Yii1 framework"
#      file: src={{ homedir }}/yii-1.1.17/framework state=link path={{ homedir }}/yii force=yes
#      when: yii.stat.islnk is not defined
#      tags: ["yii1"]
